-- Warehouses. Migrated from Terraform (warehouses.tf) to DCM.
DEFINE WAREHOUSE DEV_INGEST_WH
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'Data loading and ingestion workloads';

DEFINE WAREHOUSE DEV_TRANSFORM_WH
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 120
  AUTO_RESUME = TRUE
  COMMENT = 'dbt transformations and ELT workloads';

DEFINE WAREHOUSE DEV_REPORTING_WH
  WAREHOUSE_SIZE = 'XSMALL'
  WAREHOUSE_TYPE = 'STANDARD'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  COMMENT = 'BI tools and ad-hoc reporting queries';
