-- Grants. Tiered RBAC composition for the Customer domain: Tier 3 (database roles) + Tier 4
-- (warehouse roles) -> Tier 2 (functional roles) -> Tier 1 (persona roles). See roles.sql /
-- database_roles.sql for the role definitions this file wires together.

-- Visibility: persona roles report up to SYSADMIN (consistent with the rest of this project)
GRANT ROLE DEV_CUSTOMER_DATA_ENGINEER_PRSN TO ROLE SYSADMIN;
GRANT ROLE DEV_CUSTOMER_DATA_ANALYST_PRSN TO ROLE SYSADMIN;
GRANT ROLE DEV_CUSTOMER_DATA_CONSUMER_PRSN TO ROLE SYSADMIN;
GRANT ROLE DEV_CUSTOMER_DBT_SERVICE_PRSN TO ROLE SYSADMIN;

-- Least-privilege grant to the actual dbt CI identity (Terraform-created in
-- oidc_service_user.tf, Repo 1) — demonstrates the tiered RBAC model end-to-end for a real
-- downstream workload: this user gets nothing but this one persona role.
GRANT ROLE DEV_CUSTOMER_DBT_SERVICE_PRSN TO USER GITHUB_DEV_DBT_SVC;

-- Lets SECURITYADMIN create masking/row-access policies in DEV_CUSTOMER_DB.SHARED
GRANT CREATE MASKING POLICY, CREATE ROW ACCESS POLICY ON SCHEMA DEV_CUSTOMER_DB.SHARED TO ROLE SECURITYADMIN;

-- Tier 4: warehouse role hierarchy (USAGE -> MONITOR -> OPERATE) + privilege grants.
-- Account-level shared compute — not domain-specific (see roles.sql).
GRANT ROLE DEV_INGEST_WH_WHRL_U TO ROLE DEV_INGEST_WH_WHRL_M;
GRANT ROLE DEV_INGEST_WH_WHRL_M TO ROLE DEV_INGEST_WH_WHRL_O;
GRANT USAGE ON WAREHOUSE DEV_INGEST_WH TO ROLE DEV_INGEST_WH_WHRL_U;
GRANT MONITOR ON WAREHOUSE DEV_INGEST_WH TO ROLE DEV_INGEST_WH_WHRL_M;
GRANT OPERATE ON WAREHOUSE DEV_INGEST_WH TO ROLE DEV_INGEST_WH_WHRL_O;

GRANT ROLE DEV_TRANSFORM_WH_WHRL_U TO ROLE DEV_TRANSFORM_WH_WHRL_M;
GRANT ROLE DEV_TRANSFORM_WH_WHRL_M TO ROLE DEV_TRANSFORM_WH_WHRL_O;
GRANT USAGE ON WAREHOUSE DEV_TRANSFORM_WH TO ROLE DEV_TRANSFORM_WH_WHRL_U;
GRANT MONITOR ON WAREHOUSE DEV_TRANSFORM_WH TO ROLE DEV_TRANSFORM_WH_WHRL_M;
GRANT OPERATE ON WAREHOUSE DEV_TRANSFORM_WH TO ROLE DEV_TRANSFORM_WH_WHRL_O;

GRANT ROLE DEV_REPORTING_WH_WHRL_U TO ROLE DEV_REPORTING_WH_WHRL_M;
GRANT ROLE DEV_REPORTING_WH_WHRL_M TO ROLE DEV_REPORTING_WH_WHRL_O;
GRANT USAGE ON WAREHOUSE DEV_REPORTING_WH TO ROLE DEV_REPORTING_WH_WHRL_U;
GRANT MONITOR ON WAREHOUSE DEV_REPORTING_WH TO ROLE DEV_REPORTING_WH_WHRL_M;
GRANT OPERATE ON WAREHOUSE DEV_REPORTING_WH TO ROLE DEV_REPORTING_WH_WHRL_O;

-- Tier 3: database role hierarchy (write includes read) + privilege grants, within DEV_CUSTOMER_DB
GRANT DATABASE ROLE DEV_CUSTOMER_DB.RAW_SCRL_R TO DATABASE ROLE DEV_CUSTOMER_DB.RAW_SCRL_W;
GRANT USAGE ON DATABASE DEV_CUSTOMER_DB TO DATABASE ROLE DEV_CUSTOMER_DB.RAW_SCRL_R;
GRANT USAGE ON SCHEMA DEV_CUSTOMER_DB.RAW TO DATABASE ROLE DEV_CUSTOMER_DB.RAW_SCRL_R;
GRANT SELECT ON ALL TABLES IN SCHEMA DEV_CUSTOMER_DB.RAW TO DATABASE ROLE DEV_CUSTOMER_DB.RAW_SCRL_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_CUSTOMER_DB.RAW TO DATABASE ROLE DEV_CUSTOMER_DB.RAW_SCRL_R;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA DEV_CUSTOMER_DB.RAW TO DATABASE ROLE DEV_CUSTOMER_DB.RAW_SCRL_W;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA DEV_CUSTOMER_DB.RAW TO DATABASE ROLE DEV_CUSTOMER_DB.RAW_SCRL_W;

GRANT DATABASE ROLE DEV_CUSTOMER_DB.STAGING_SCRL_R TO DATABASE ROLE DEV_CUSTOMER_DB.STAGING_SCRL_W;
GRANT USAGE ON DATABASE DEV_CUSTOMER_DB TO DATABASE ROLE DEV_CUSTOMER_DB.STAGING_SCRL_R;
GRANT USAGE ON SCHEMA DEV_CUSTOMER_DB.STAGING TO DATABASE ROLE DEV_CUSTOMER_DB.STAGING_SCRL_R;
GRANT SELECT ON ALL TABLES IN SCHEMA DEV_CUSTOMER_DB.STAGING TO DATABASE ROLE DEV_CUSTOMER_DB.STAGING_SCRL_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_CUSTOMER_DB.STAGING TO DATABASE ROLE DEV_CUSTOMER_DB.STAGING_SCRL_R;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA DEV_CUSTOMER_DB.STAGING TO DATABASE ROLE DEV_CUSTOMER_DB.STAGING_SCRL_W;
GRANT INSERT, UPDATE, DELETE, TRUNCATE ON FUTURE TABLES IN SCHEMA DEV_CUSTOMER_DB.STAGING TO DATABASE ROLE DEV_CUSTOMER_DB.STAGING_SCRL_W;

GRANT USAGE ON DATABASE DEV_CUSTOMER_DB TO DATABASE ROLE DEV_CUSTOMER_DB.MARTS_SCRL_R;
GRANT USAGE ON SCHEMA DEV_CUSTOMER_DB.MARTS TO DATABASE ROLE DEV_CUSTOMER_DB.MARTS_SCRL_R;
GRANT SELECT ON ALL TABLES IN SCHEMA DEV_CUSTOMER_DB.MARTS TO DATABASE ROLE DEV_CUSTOMER_DB.MARTS_SCRL_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_CUSTOMER_DB.MARTS TO DATABASE ROLE DEV_CUSTOMER_DB.MARTS_SCRL_R;

GRANT USAGE ON DATABASE DEV_CUSTOMER_DB TO DATABASE ROLE DEV_CUSTOMER_DB.SHARED_SCRL_R;
GRANT USAGE ON SCHEMA DEV_CUSTOMER_DB.SHARED TO DATABASE ROLE DEV_CUSTOMER_DB.SHARED_SCRL_R;
GRANT SELECT ON ALL TABLES IN SCHEMA DEV_CUSTOMER_DB.SHARED TO DATABASE ROLE DEV_CUSTOMER_DB.SHARED_SCRL_R;
GRANT SELECT ON FUTURE TABLES IN SCHEMA DEV_CUSTOMER_DB.SHARED TO DATABASE ROLE DEV_CUSTOMER_DB.SHARED_SCRL_R;

-- Tier 2: functional roles composed from Tier 3 (database) + Tier 4 (warehouse) roles
GRANT DATABASE ROLE DEV_CUSTOMER_DB.RAW_SCRL_W TO ROLE DEV_CUSTOMER_INGEST_FNCRL;
GRANT ROLE DEV_INGEST_WH_WHRL_U TO ROLE DEV_CUSTOMER_INGEST_FNCRL;

GRANT DATABASE ROLE DEV_CUSTOMER_DB.RAW_SCRL_R TO ROLE DEV_CUSTOMER_TRANSFORM_FNCRL;
GRANT DATABASE ROLE DEV_CUSTOMER_DB.STAGING_SCRL_W TO ROLE DEV_CUSTOMER_TRANSFORM_FNCRL;
GRANT DATABASE ROLE DEV_CUSTOMER_DB.SHARED_SCRL_R TO ROLE DEV_CUSTOMER_TRANSFORM_FNCRL;
GRANT ROLE DEV_TRANSFORM_WH_WHRL_U TO ROLE DEV_CUSTOMER_TRANSFORM_FNCRL;

GRANT DATABASE ROLE DEV_CUSTOMER_DB.MARTS_SCRL_R TO ROLE DEV_CUSTOMER_READER_FNCRL;
GRANT ROLE DEV_REPORTING_WH_WHRL_U TO ROLE DEV_CUSTOMER_READER_FNCRL;

-- Tier 1: personas receive the functional roles they need (engineers additionally get
-- OPERATE on the ingest warehouse, since they're the ones who'd resize/resume it)
GRANT ROLE DEV_CUSTOMER_INGEST_FNCRL TO ROLE DEV_CUSTOMER_DATA_ENGINEER_PRSN;
GRANT ROLE DEV_INGEST_WH_WHRL_O TO ROLE DEV_CUSTOMER_DATA_ENGINEER_PRSN;

GRANT ROLE DEV_CUSTOMER_TRANSFORM_FNCRL TO ROLE DEV_CUSTOMER_DBT_SERVICE_PRSN;

GRANT ROLE DEV_CUSTOMER_READER_FNCRL TO ROLE DEV_CUSTOMER_DATA_ANALYST_PRSN;
GRANT ROLE DEV_CUSTOMER_READER_FNCRL TO ROLE DEV_CUSTOMER_DATA_CONSUMER_PRSN;
