name: Terraform Apply

on:
  push:
    branches: [main]
    paths:
      - "*.tf"
      - "env/**"
      - ".github/workflows/terraform-apply.yml"
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, qa, prod)"
        required: true
        default: "dev"
        type: choice
        options:
          - dev
          - qa
          - prod

permissions:
  contents: read
  id-token: write

jobs:
  apply:
    name: Terraform Apply
    runs-on: ubuntu-latest

    env:
      TF_VAR_snowflake_organization_name: xygpmhm
      TF_VAR_snowflake_account_name: gq04150
      TARGET_ENV: ${{ github.event.inputs.environment || 'dev' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::525218385225:role/snowflake-platform-tf-github-oidc
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.16.0"

      - name: Write Snowflake private key
        run: |
          mkdir -p ~/.ssh/snowflake
          echo "${{ secrets.SNOWFLAKE_PRIVATE_KEY }}" > ~/.ssh/snowflake/tf_snow_key.p8
          chmod 600 ~/.ssh/snowflake/tf_snow_key.p8

      - name: Terraform Init
        run: terraform init -backend-config="env/${{ env.TARGET_ENV }}/backend.hcl"

      - name: Terraform Apply
        run: terraform apply -var-file="env/${{ env.TARGET_ENV }}/${{ env.TARGET_ENV }}.tfvars" -auto-approve
